### PR TITLE
Added Lucas O'Reilly to District 3 Unit 5

### PR DESCRIPTION
**Pull request by MaxwellKJr**
## Updates
- Added Lucas O'Reilly to District 3 Unit 5
- Added Madina Huka as a Sendss Contact in District 3 Unit 5

### CODE REVIEW

**Review by yago1994 — CHANGES_REQUESTED** [review]
Looks mostly good but a couple things 
1. Seems like you changed the formatting, perhaps the IDE by itself, so effectively all the file changed! Makes it very hard to review the PR effectively just looking at code 😢 
2. This person, Laverna, has changed too, see below
image
3. Also District 8 Unit 2
image

**Comment by yago1994** [comment]
@charlotteyao-emory I did a pass and noted a couple of those things missing, after Max fixes it can you take a pass?

**Comment by yago1994** [comment]
@charlotteyao-emory any update reviewing this?

**Comment by MaxwellKJr** [comment]
@yago1994 @charlotteyao-emory I made the changes

**Review by yago1994 — APPROVED** [review]
@MaxwellKJr Looks good! Merge and move over this change to the iOS version. You can raise a PR and merge it right away for documentation. I don't think I need to review it. 

Make sure to change the date for the TB coordinators updated time to September 2024

**Pull request merged**
