### PR TITLE
Added Tonya Burke as the new TB Coordinator for District 8-2

### PR DESCRIPTION
**Pull request by MaxwellKJr**
> Also, Juanita Martin in District 3-5 has retired; a replacement has not yet been announced.

Should I remove Juanita Martin in this case?

### CODE REVIEW

**Comment by yago1994** [comment]
@MaxwellKJr yes, you can just leave the field as VACANT like in the table

image

**Comment by yago1994** [comment]
Also remove the content here
image

Make sure to compare with the provided file to make sure it matches up! That is the latest version even if some things haven't been specifically written, we should match the file.

**Comment by yago1994** [comment]
And this
image

**Comment by yago1994** [comment]
@MaxwellKJr did you get a chance to work on this?

**Review by yago1994 — CHANGES_REQUESTED** [review]
Some changes missing, please see my comments

**Comment by MaxwellKJr** [comment]
> @MaxwellKJr did you get a chance to work on this?

Yes. I was actually going through the document row by row and will push the updated content today

**Comment by MaxwellKJr** [comment]
@yago1994 I have made the changes and updates

**Review by yago1994 — CHANGES_REQUESTED** [review]

**Review by yago1994 — APPROVED** [review]
gif

Great job, this was a lot trickier than we thought huh? A lot of detail to swift through

**Pull request merged**
